---
title: "Data Science Specialization"
author: "Andres Camilo Zuñiga Gonzalez"
date: "24/8/2020"
output: github_document
---


This is the repository for the [Data Science Specialization](https://www.coursera.org/specializations/jhu-data-science) by Johns Hopkins University from the Coursera Platform

1. [The Data Scientist's Toolbox](https://www.coursera.org/learn/data-scientists-tools)
2. [R Programming](R_Programming)
3. [Getting and Cleaning Data](Getting_and_Cleaning_Data/)
4. [Exploratory Data Analysis](Exploratory_Data_Analysis/)
5. [Reproducible Research](Reproducible_Research/)
6. [Statistical Inference](Statistical_Inference/)
7. [Regression Models](Regression_Models/)
8. [Practical Machine Learning](Practical_Machine_Learning/)
9. [Developing Data Products](Developing_Data_Products/)
10. [Data Science Capstone](Data_Science_Capstone/)

* [Here](https://rpubs.com/ancazugo) you can see some of the published Rpubs documents for some of the assignments of the Specialization.

Feel free to use any of the code as reference for your projects.